/**
 * Copia pública de `SOURCE_TO_SITUATION` (privada al módulo `motor-v2.1.ts`,
 * líneas 280-358) — necesaria porque `motor-v1.ts` necesita mapear
 * `MotorOutput.source` a un bucket de situación para poder aplicar el
 * crosswalk a las 11 situaciones Synergy (spec 12.1), y `motor-v2.1.ts` no la
 * exporta.
 *
 * IMPORTANTE: esta tabla debe mantenerse en sincronía con la original de
 * `motor-v2.1.ts`. Es deuda técnica deliberada, no un descuido — duplicar una
 * constante es preferible a tocar `motor-v2.1.ts` (motor legado, fuera de
 * alcance de Fase 1) solo para exportar una tabla interna. Cuando Fase 3
 * (migración de consumidores) retire `motor-v2.1.ts`, este archivo deja de
 * hacer falta como copia y la tabla pasa a vivir solo aquí.
 *
 * Verificado 1:1 contra `motor-v2.1.ts:280-358` el 2026-09-11.
 */
export const SOURCE_TO_SITUATION_PUBLICA: Record<string, string> = {
  iso: "iso",
  iso_dir: "iso",
  iso_dir_confirmed: "iso",
  iso_strong_hand_finish: "iso",
  iso_weak_hand_finish: "iso",
  selfish_low_eff: "iso",
  selfish: "iso",
  pnr: "pnr",
  pnr_finish_asymmetry: "pnr",
  pnr_shooter_weak_side: "pnr",
  trap_response: "pnr",
  escape_pass_first: "pnr",
  screener_roll: "screener",
  screener_pop: "screener",
  screener_pop_no_range: "screener",
  screener_slip: "screener",
  screen_timing: "screener",
  data_inconsistency: "screener",
  post: "post",
  post_channel: "post",
  post_shoulder: "post",
  post_entry_duck_in: "post",
  post_entry_seal: "post",
  post_rare_efficient: "post",
  post_move_fade: "post",
  post_move_turnaround: "post",
  post_move_hook: "post",
  post_combo_hook_upunder: "post",
  no_post: "post",
  dunker_spot: "post",
  high_post: "post",
  duck_in_rim_runner_unified: "post",
  trans_rim_run: "transition",
  trans_trail: "transition",
  trans_leak: "transition",
  trans_sub: "transition",
  trans_cut_finishing: "transition",
  transition: "transition",
  transition_graded: "transition",
  corner_spot: "spot",
  corner_no_range: "spot",
  no_deep_range: "spot",
  deep_range: "spot",
  dho: "dho",
  cut: "cut",
  cut_compulsive_unified: "cut",
  oreb: "oreb",
  oreb_finisher: "oreb",
  oreb_distributor: "oreb",
  oreb_medium: "oreb",
  oreb_threat: "oreb",
  off_ball_screen: "offball",
  off_ball_cut: "offball",
  off_ball_roll_rim: "offball",
  off_ball_screen_graded: "offball",
  off_ball_role: "offball",
  floater: "floater",
  pnr_floater_unified: "pnr",
  contact_avoids: "misc",
  off_hand: "misc",
  contact_weak_hand_combined: "misc",
  self_creation: "misc",
  vision: "misc",
  physical: "misc",
  both_hands: "misc",
  connector: "misc",
  weak_iso: "misc",
  ball_handling_liability: "misc",
  limited_handling_struggles: "misc",
  ball_handling_limited: "misc",
  pressure_struggles: "misc",
  no_range_no_threat: "misc",
  gender_f_interior: "misc",
  oreb_and_transition: "oreb",
  no_range_spot_active: "spot",
  interior_low_impact: "misc",
  selfish_exploitable: "misc",
};
