// ─── U Scout Motor Test Suite ─────────────────────────────────────────────────
// 64 real players with documented tendencies + expected archetypes
// Run independently or via TestMode batch tab
// Last updated: March 2026

export interface TestPlayer {
  name: string;
  position: string;
  expected: string;
  league: "NBA" | "WNBA" | "EuroLeague" | "Generic";
  // Physical
  ath: 0|1|2|3|4|5;
  phys: 0|1|2|3|4|5;
  vision: 0|1|2|3|4|5;
  ft?: 0|1|2|3|4|5;
  foul?: 0|1|2|3|4|5;
  // Post
  pF: "Primary"|"Secondary"|"Rare"|"Never";
  hasQ?: boolean;
  pPro?: string;
  // ISO
  iF: "Primary"|"Secondary"|"Rare"|"Never";
  iDec?: "Finish"|"Shoot"|"Pass";
  iDir?: "Left"|"Right"|"Balanced";
  co?: string;
  perim?: "Primary"|"Secondary"|"Rare"|"Never";
  // PnR
  pnrF: "Primary"|"Secondary"|"Rare"|"Never";
  pnrRole: "Handler"|"Screener"|"Both";
  pnrRS?: "Handler"|"Screener"|"Balanced";
  pnrP?: "Score First"|"Pass First"|"Balanced";
  vsU?: "Pull-up 3"|"Re-screen"|"Reject / Attack";
  sA?: string;
  // Off-ball
  tF: "Primary"|"Secondary"|"Rare"|"Never";
  tR?: string;
  indF?: "Primary"|"Secondary"|"Rare"|"Never";
  bkF?: "Primary"|"Secondary"|"Rare"|"Never";
  offReb?: "Primary"|"Secondary"|"Rare"|"Never";
}

export const TEST_SUITE: TestPlayer[] = [
  // ── NBA Guards ─────────────────────────────────────────────────────────────
  { name:"Nikola Jokic",           league:"NBA",       position:"C",   expected:"Versatile Big",          ath:2,phys:4,vision:5, pF:"Primary",  hasQ:true, pPro:"Mixed",          iF:"Secondary",iDec:"Pass",  iDir:"Balanced",co:"Extra Pass",    pnrF:"Primary",  pnrRole:"Handler",  pnrP:"Pass First", vsU:"Pull-up 3",      tF:"Secondary",indF:"Rare",    bkF:"Rare"   },
  { name:"Luka Doncic",            league:"NBA",       position:"G/F", expected:"Offensive Engine",       ath:3,phys:4,vision:4, pF:"Secondary",hasQ:true,                         iF:"Primary",  iDec:"Finish",iDir:"Left",    co:"Attack Middle", pnrF:"Primary",  pnrRole:"Handler",  pnrP:"Balanced",   vsU:"Pull-up 3",      tF:"Secondary",indF:"Rare",    bkF:"Rare"   },
  { name:"Stephen Curry",          league:"NBA",       position:"PG",  expected:"Movement Shooter",       ath:4,phys:2,vision:4, pF:"Never",                                       iF:"Secondary",iDec:"Shoot", iDir:"Right",   co:"Catch & Shoot", pnrF:"Primary",  pnrRole:"Handler",  pnrP:"Score First",vsU:"Pull-up 3",      tF:"Secondary",indF:"Primary", bkF:"Rare"   },
  { name:"Trae Young",             league:"NBA",       position:"PG",  expected:"PnR Maestro",            ath:2,phys:1,vision:5, pF:"Never",                                       iF:"Secondary",iDec:"Shoot", iDir:"Left",    co:"Catch & Shoot", pnrF:"Primary",  pnrRole:"Handler",  pnrP:"Pass First", vsU:"Pull-up 3",      tF:"Secondary",indF:"Rare",    bkF:"Rare"   },
  { name:"Shai Gilgeous-Alexander",league:"NBA",       position:"G",   expected:"Isolation Driver",       ath:4,phys:3,vision:3, pF:"Rare",                                        iF:"Primary",  iDec:"Finish",iDir:"Left",    co:"Attack Middle", pnrF:"Secondary",pnrRole:"Handler",  pnrP:"Score First",vsU:"Reject / Attack",tF:"Secondary",indF:"Rare",    bkF:"Rare"   },
  { name:"Kyrie Irving",           league:"NBA",       position:"PG",  expected:"Shot Creator",           ath:4,phys:2,vision:3, pF:"Rare",                                        iF:"Primary",  iDec:"Shoot", iDir:"Left",    co:"Attack Middle", pnrF:"Secondary",pnrRole:"Handler",  pnrP:"Score First",vsU:"Pull-up 3",      tF:"Secondary",indF:"Secondary",bkF:"Rare"   },
  { name:"Anthony Edwards",        league:"NBA",       position:"SG",  expected:"Isolation Driver",       ath:5,phys:4,vision:2, pF:"Rare",                                        iF:"Primary",  iDec:"Finish",iDir:"Right",   co:"Attack Baseline",pnrF:"Secondary",pnrRole:"Handler", pnrP:"Score First",vsU:"Reject / Attack",tF:"Primary",  indF:"Rare",    bkF:"Rare",  tR:"Pusher"   },
  { name:"Devin Booker",           league:"NBA",       position:"SG",  expected:"Shot Creator",           ath:3,phys:3,vision:3, pF:"Secondary",                                   iF:"Primary",  iDec:"Shoot", iDir:"Right",   co:"Catch & Shoot", pnrF:"Secondary",pnrRole:"Handler",  pnrP:"Score First",vsU:"Pull-up 3",      tF:"Rare",     indF:"Secondary",bkF:"Rare"   },
  { name:"Klay Thompson",          league:"NBA",       position:"SG",  expected:"Movement Shooter",       ath:3,phys:3,vision:2, pF:"Never",                                       iF:"Secondary",iDec:"Shoot", iDir:"Right",   co:"Catch & Shoot", pnrF:"Rare",     pnrRole:"Handler",  pnrP:"Score First",vsU:"Pull-up 3",      tF:"Secondary",indF:"Primary", bkF:"Rare"   },
  { name:"Damian Lillard",         league:"NBA",       position:"PG",  expected:"PnR Shooter",            ath:3,phys:2,vision:3, pF:"Never",                                       iF:"Secondary",iDec:"Shoot", iDir:"Right",   co:"Catch & Shoot", pnrF:"Primary",  pnrRole:"Handler",  pnrP:"Score First",vsU:"Pull-up 3",      tF:"Secondary",indF:"Secondary",bkF:"Rare"   },
  // ── NBA Wings ──────────────────────────────────────────────────────────────
  { name:"LeBron James",           league:"NBA",       position:"F/G", expected:"Offensive Engine",       ath:5,phys:5,vision:4, pF:"Secondary",hasQ:true,                         iF:"Primary",  iDec:"Finish",iDir:"Left",    co:"Attack Middle", pnrF:"Primary",  pnrRole:"Handler",  pnrP:"Balanced",   vsU:"Reject / Attack",tF:"Primary",  indF:"Rare",    bkF:"Rare",  tR:"Pusher"   },
  { name:"Giannis Antetokounmpo",  league:"NBA",       position:"F/C", expected:"Multi-Level Scorer",     ath:5,phys:5,vision:3, pF:"Secondary",hasQ:true,                         iF:"Primary",  iDec:"Finish",iDir:"Right",   co:"Attack Middle", pnrF:"Primary",  pnrRole:"Handler",  pnrP:"Score First",vsU:"Reject / Attack",tF:"Primary",  indF:"Rare",    bkF:"Rare",  tR:"Rim Runner"},
  { name:"Kevin Durant",           league:"NBA",       position:"F",   expected:"Shot Creator",           ath:4,phys:3,vision:3, pF:"Secondary",                                   iF:"Primary",  iDec:"Shoot", iDir:"Balanced",co:"Catch & Shoot", pnrF:"Secondary",pnrRole:"Handler",  pnrP:"Score First",vsU:"Pull-up 3",      tF:"Secondary",indF:"Secondary",bkF:"Rare"   },
  { name:"Jayson Tatum",           league:"NBA",       position:"F",   expected:"Shot Creator",           ath:4,phys:3,vision:3, pF:"Secondary",                                   iF:"Primary",  iDec:"Shoot", iDir:"Right",   co:"Catch & Shoot", pnrF:"Secondary",pnrRole:"Handler",  pnrP:"Score First",vsU:"Pull-up 3",      tF:"Secondary",indF:"Secondary",bkF:"Rare"   },
  { name:"Kawhi Leonard",          league:"NBA",       position:"F",   expected:"Shot Creator",           ath:4,phys:4,vision:3, pF:"Secondary",                                   iF:"Primary",  iDec:"Shoot", iDir:"Right",   co:"Catch & Shoot", pnrF:"Rare",     pnrRole:"Handler",  pnrP:"Score First",vsU:"Pull-up 3",      tF:"Secondary",indF:"Secondary",bkF:"Rare"   },
  { name:"Draymond Green",         league:"NBA",       position:"F/C", expected:"Playmaking Big",         ath:3,phys:4,vision:5, pF:"Rare",                                        iF:"Rare",     iDec:"Pass",  iDir:"Balanced",co:"Extra Pass",    pnrF:"Primary",  pnrRole:"Both",     pnrRS:"Screener",  pnrP:"Pass First", vsU:"Re-screen",     sA:"Short Roll",tF:"Secondary",indF:"Rare",bkF:"Rare" },
  { name:"Santi Aldama",           league:"NBA",       position:"F/C", expected:"Stretch Big",            ath:3,phys:3,vision:3, pF:"Rare",                                        iF:"Rare",     iDec:"Shoot", iDir:"Balanced",co:"Catch & Shoot", pnrF:"Secondary",pnrRole:"Screener", pnrP:"Balanced",   sA:"Pop (Elbow / Mid)",               tF:"Secondary",indF:"Rare",    bkF:"Rare"   },
  // ── NBA Bigs ───────────────────────────────────────────────────────────────
  { name:"Joel Embiid",            league:"NBA",       position:"C",   expected:"Multi-Level Scorer",     ath:3,phys:5,vision:3, pF:"Primary",  hasQ:true, pPro:"Back to Basket",  iF:"Primary",  iDec:"Shoot", iDir:"Right",   co:"Catch & Shoot", pnrF:"Secondary",pnrRole:"Handler",  pnrP:"Score First",vsU:"Pull-up 3",      tF:"Rare",     indF:"Rare",    bkF:"Rare"   },
  { name:"Victor Wembanyama",      league:"NBA",       position:"C",   expected:"Multi-Level Scorer",     ath:5,phys:2,vision:3, pF:"Secondary",hasQ:true, pPro:"High Post",        iF:"Primary",  iDec:"Shoot", iDir:"Right",   co:"Catch & Shoot", pnrF:"Secondary",pnrRole:"Screener", sA:"Pop",                               tF:"Primary",  indF:"Secondary",bkF:"Secondary",tR:"Rim Runner"},
  { name:"Rudy Gobert",            league:"NBA",       position:"C",   expected:"Roll Man / Lob Threat",  ath:3,phys:5,vision:2, pF:"Secondary",                                   iF:"Never",                  iDir:"Balanced",co:"Extra Pass",    pnrF:"Primary",  pnrRole:"Screener", sA:"Roll",                              tF:"Primary",  indF:"Rare",    bkF:"Rare",  tR:"Rim Runner"},
  { name:"Bam Adebayo",            league:"NBA",       position:"F/C", expected:"Playmaking Big",         ath:4,phys:4,vision:4, pF:"Secondary",            pPro:"Face-Up",          iF:"Rare",                   iDir:"Balanced",co:"Extra Pass",    pnrF:"Primary",  pnrRole:"Both",     pnrRS:"Handler",   pnrP:"Pass First", vsU:"Re-screen",     sA:"Short Roll",tF:"Secondary",indF:"Rare",bkF:"Rare",tR:"Rim Runner"},
  { name:"Brook Lopez",            league:"NBA",       position:"C",   expected:"Stretch Big",            ath:2,phys:3,vision:2, pF:"Never",                                       iF:"Never",                  iDir:"Balanced",co:"Catch & Shoot", pnrF:"Primary",  pnrRole:"Screener", sA:"Pop",                               tF:"Rare",     indF:"Rare",    bkF:"Rare"   },
  { name:"Karl-Anthony Towns",     league:"NBA",       position:"F/C", expected:"Stretch Big",            ath:3,phys:4,vision:3, pF:"Secondary",            pPro:"Stretch Big",      iF:"Secondary",iDec:"Shoot", iDir:"Balanced",co:"Catch & Shoot", pnrF:"Primary",  pnrRole:"Screener", sA:"Pop",                               tF:"Secondary",indF:"Rare",    bkF:"Rare"   },
  { name:"Kenyon Lofton Jr.",      league:"NBA",       position:"F/C", expected:"Low Post Scorer",        ath:3,phys:4,vision:3, pF:"Primary",  hasQ:true, pPro:"Back to Basket",  iF:"Rare",     iDec:"Finish",iDir:"Left",    co:"Attack Baseline",pnrF:"Secondary",pnrRole:"Both",     pnrRS:"Screener",  pnrP:"Score First",vsU:"Re-screen",     sA:"Short Roll",tF:"Secondary",indF:"Rare",bkF:"Rare",offReb:"Primary"},
  { name:"James Harden",           league:"NBA",       position:"G",   expected:"Offensive Engine",       ath:3,phys:3,vision:4, pF:"Secondary",            pPro:"Face-Up",          iF:"Primary",  iDec:"Shoot", iDir:"Left",    co:"Catch & Shoot", pnrF:"Primary",  pnrRole:"Handler",  pnrP:"Balanced",   vsU:"Pull-up 3",      tF:"Secondary",indF:"Rare",    bkF:"Rare"   },
  { name:"Chris Paul",             league:"NBA",       position:"PG",  expected:"PnR Maestro",            ath:2,phys:2,vision:5, pF:"Never",                                       iF:"Secondary",iDec:"Shoot", iDir:"Right",   co:"Catch & Shoot", pnrF:"Primary",  pnrRole:"Handler",  pnrP:"Pass First", vsU:"Pull-up 3",      tF:"Secondary",indF:"Rare",    bkF:"Rare"   },
  { name:"Domantas Sabonis",       league:"NBA",       position:"F/C", expected:"Versatile Big",          ath:2,phys:4,vision:4, pF:"Primary",  hasQ:true, pPro:"Mixed",           iF:"Secondary",iDec:"Pass",  iDir:"Balanced",co:"Extra Pass",    pnrF:"Primary",  pnrRole:"Handler",  pnrP:"Pass First", vsU:"Pull-up 3",      tF:"Secondary",indF:"Rare",    bkF:"Rare",  tR:"Trailer"  },
  { name:"De'Aaron Fox",           league:"NBA",       position:"PG",  expected:"Isolation Driver",       ath:5,phys:3,vision:3, pF:"Never",                                       iF:"Primary",  iDec:"Finish",iDir:"Left",    co:"Attack Middle", pnrF:"Secondary",pnrRole:"Handler",  pnrP:"Score First",vsU:"Reject / Attack",tF:"Primary",  indF:"Rare",    bkF:"Rare",  tR:"Pusher"   },
  { name:"Tyrese Haliburton",      league:"NBA",       position:"PG",  expected:"PnR Maestro",            ath:3,phys:2,vision:5, pF:"Never",                                       iF:"Secondary",iDec:"Shoot", iDir:"Left",    co:"Catch & Shoot", pnrF:"Primary",  pnrRole:"Handler",  pnrP:"Pass First", vsU:"Pull-up 3",      tF:"Primary",  indF:"Secondary",bkF:"Rare",  tR:"Pusher"   },
  // ── WNBA ───────────────────────────────────────────────────────────────────
  { name:"A'ja Wilson",            league:"WNBA",      position:"F/C", expected:"Traditional Post Scorer",ath:4,phys:5,vision:3, pF:"Primary",  hasQ:true, pPro:"Back to Basket",  iF:"Secondary",iDec:"Finish",iDir:"Right",   co:"Attack Baseline",pnrF:"Rare",     pnrRole:"Screener", sA:"Roll",                              tF:"Secondary",indF:"Rare",    bkF:"Rare",  tR:"Rim Runner",offReb:"Primary"},
  { name:"Breanna Stewart",        league:"WNBA",      position:"F/C", expected:"Multi-Level Scorer",     ath:4,phys:4,vision:3, pF:"Primary",  hasQ:true, pPro:"Mixed",           iF:"Primary",  iDec:"Shoot", iDir:"Right",   co:"Catch & Shoot", pnrF:"Secondary",pnrRole:"Handler",  pnrP:"Score First",vsU:"Pull-up 3",      tF:"Secondary",indF:"Secondary",bkF:"Rare"   },
  { name:"Sabrina Ionescu",        league:"WNBA",      position:"PG",  expected:"PnR Shooter",            ath:3,phys:2,vision:4, pF:"Never",                                       iF:"Secondary",iDec:"Shoot", iDir:"Left",    co:"Catch & Shoot", pnrF:"Primary",  pnrRole:"Handler",  pnrP:"Balanced",   vsU:"Pull-up 3",      tF:"Secondary",indF:"Primary", bkF:"Rare"   },
  { name:"Diana Taurasi",          league:"WNBA",      position:"G",   expected:"Shot Creator",           ath:3,phys:2,vision:3, pF:"Never",                                       iF:"Primary",  iDec:"Shoot", iDir:"Right",   co:"Catch & Shoot", pnrF:"Secondary",pnrRole:"Handler",  pnrP:"Score First",vsU:"Pull-up 3",      tF:"Secondary",indF:"Primary", bkF:"Rare"   },
  { name:"Napheesa Collier",       league:"WNBA",      position:"F",   expected:"Isolation Driver",       ath:4,phys:4,vision:3, pF:"Rare",                                        iF:"Primary",  iDec:"Finish",iDir:"Right",   co:"Attack Middle", pnrF:"Secondary",pnrRole:"Handler",  pnrP:"Score First",vsU:"Reject / Attack",tF:"Secondary",indF:"Rare",    bkF:"Rare"   },
  { name:"Kelsey Plum",            league:"WNBA",      position:"G",   expected:"Shot Creator",           ath:3,phys:2,vision:3, pF:"Never",                                       iF:"Primary",  iDec:"Shoot", iDir:"Left",    co:"Catch & Shoot", pnrF:"Secondary",pnrRole:"Handler",  pnrP:"Score First",vsU:"Pull-up 3",      tF:"Secondary",indF:"Secondary",bkF:"Rare"   },
  { name:"Kalani Brown",           league:"WNBA",      position:"C",   expected:"Traditional Post Scorer",ath:2,phys:5,vision:2, pF:"Primary",  hasQ:true, pPro:"Back to Basket",  iF:"Never",                  iDir:"Balanced",co:"Extra Pass",    pnrF:"Never",    pnrRole:"Screener", sA:"Roll",                              tF:"Never",    indF:"Never",   bkF:"Never"  },
  { name:"Caitlin Clark",          league:"WNBA",      position:"PG",  expected:"PnR Maestro",            ath:3,phys:2,vision:5, pF:"Never",                                       iF:"Secondary",iDec:"Shoot", iDir:"Right",   co:"Catch & Shoot", pnrF:"Primary",  pnrRole:"Handler",  pnrP:"Balanced",   vsU:"Pull-up 3",      tF:"Secondary",indF:"Secondary",bkF:"Rare"   },
  { name:"Arike Ogunbowale",       league:"WNBA",      position:"G",   expected:"Offensive Engine",       ath:4,phys:3,vision:3, pF:"Never",                                       iF:"Primary",  iDec:"Shoot", iDir:"Right",   co:"Catch & Shoot", pnrF:"Primary",  pnrRole:"Handler",  pnrP:"Score First",vsU:"Pull-up 3",      tF:"Secondary",indF:"Secondary",bkF:"Rare"   },
  { name:"Jonquel Jones",          league:"WNBA",      position:"F/C", expected:"Multi-Level Scorer",     ath:3,phys:4,vision:3, pF:"Primary",  hasQ:true, pPro:"Mixed",           iF:"Secondary",iDec:"Shoot", iDir:"Balanced",co:"Catch & Shoot", pnrF:"Secondary",pnrRole:"Both",     pnrRS:"Screener",  pnrP:"Score First",vsU:"Re-screen",     sA:"Pop",  tF:"Secondary",indF:"Rare",bkF:"Rare",perim:"Primary"},
  { name:"Angel Reese",            league:"WNBA",      position:"F/C", expected:"Traditional Post Scorer",ath:3,phys:4,vision:2, pF:"Primary",  hasQ:true, pPro:"Back to Basket",  iF:"Never",                  iDir:"Balanced",co:"Attack Baseline",pnrF:"Never",    pnrRole:"Screener", sA:"Roll",                              tF:"Secondary",indF:"Never",   bkF:"Never", tR:"Rim Runner",offReb:"Primary"},
  { name:"Paige Bueckers",         league:"WNBA",      position:"PG",  expected:"PnR Maestro",            ath:4,phys:2,vision:4, pF:"Never",                                       iF:"Secondary",iDec:"Shoot", iDir:"Left",    co:"Catch & Shoot", pnrF:"Primary",  pnrRole:"Handler",  pnrP:"Pass First", vsU:"Pull-up 3",      tF:"Secondary",indF:"Secondary",bkF:"Rare"   },
  { name:"Alyssa Thomas",          league:"WNBA",      position:"F/C", expected:"Playmaking Big",         ath:3,phys:4,vision:5, pF:"Secondary",            pPro:"Face-Up",          iF:"Rare",     iDec:"Pass",  iDir:"Balanced",co:"Extra Pass",    pnrF:"Primary",  pnrRole:"Both",     pnrRS:"Handler",   pnrP:"Pass First", vsU:"Re-screen",     sA:"Short Roll",tF:"Secondary",indF:"Rare",bkF:"Rare",tR:"Rim Runner"},
  // ── EuroLeague ─────────────────────────────────────────────────────────────
  { name:"Bogdan Bogdanovic",      league:"EuroLeague",position:"G/F", expected:"Shot Creator",           ath:3,phys:3,vision:3, pF:"Never",                                       iF:"Primary",  iDec:"Shoot", iDir:"Right",   co:"Catch & Shoot", pnrF:"Secondary",pnrRole:"Handler",  pnrP:"Score First",vsU:"Pull-up 3",      tF:"Secondary",indF:"Secondary",bkF:"Rare"   },
  { name:"Shane Larkin",           league:"EuroLeague",position:"PG",  expected:"Offensive Engine",       ath:4,phys:2,vision:3, pF:"Never",                                       iF:"Primary",  iDec:"Finish",iDir:"Left",    co:"Attack Middle", pnrF:"Primary",  pnrRole:"Handler",  pnrP:"Score First",vsU:"Reject / Attack",tF:"Primary",  indF:"Rare",    bkF:"Rare",  tR:"Pusher"   },
  { name:"Vassilis Spanoulis",     league:"EuroLeague",position:"PG",  expected:"PnR Maestro",            ath:2,phys:2,vision:4, pF:"Never",                                       iF:"Secondary",iDec:"Shoot", iDir:"Right",   co:"Catch & Shoot", pnrF:"Primary",  pnrRole:"Handler",  pnrP:"Pass First", vsU:"Pull-up 3",      tF:"Rare",     indF:"Secondary",bkF:"Rare"   },
  { name:"Jan Vesely",             league:"EuroLeague",position:"C",   expected:"Roll Man / Lob Threat",  ath:4,phys:3,vision:2, pF:"Rare",                                        iF:"Never",                  iDir:"Balanced",co:"Extra Pass",    pnrF:"Primary",  pnrRole:"Screener", sA:"Roll",                              tF:"Secondary",indF:"Rare",    bkF:"Rare",  tR:"Rim Runner"},
  { name:"Nando De Colo",          league:"EuroLeague",position:"G",   expected:"Shot Creator",           ath:3,phys:2,vision:3, pF:"Never",                                       iF:"Primary",  iDec:"Shoot", iDir:"Right",   co:"Catch & Shoot", pnrF:"Secondary",pnrRole:"Handler",  pnrP:"Score First",vsU:"Pull-up 3",      tF:"Secondary",indF:"Secondary",bkF:"Rare"   },
  { name:"Nikola Mirotic",         league:"EuroLeague",position:"F/C", expected:"Multi-Level Scorer",     ath:3,phys:4,vision:3, pF:"Secondary",            pPro:"Face-Up",          iF:"Primary",  iDec:"Shoot", iDir:"Right",   co:"Catch & Shoot", pnrF:"Secondary",pnrRole:"Screener", sA:"Pop",          perim:"Primary",      tF:"Secondary",indF:"Secondary",bkF:"Rare"   },
  { name:"Sergio Rodriguez",       league:"EuroLeague",position:"PG",  expected:"PnR Maestro",            ath:2,phys:2,vision:5, pF:"Never",                                       iF:"Rare",     iDec:"Pass",  iDir:"Balanced",co:"Extra Pass",    pnrF:"Primary",  pnrRole:"Handler",  pnrP:"Pass First", vsU:"Pull-up 3",      tF:"Rare",     indF:"Secondary",bkF:"Rare"   },
  { name:"Scottie Pippen Jr.",     league:"EuroLeague",position:"G",   expected:"Isolation Driver",       ath:4,phys:2,vision:3, pF:"Never",                                       iF:"Primary",  iDec:"Finish",iDir:"Right",   co:"Attack Middle", pnrF:"Secondary",pnrRole:"Handler",  pnrP:"Score First",vsU:"Reject / Attack",tF:"Primary",  indF:"Rare",    bkF:"Rare",  tR:"Pusher"   },
  { name:"Facundo Campazzo",       league:"EuroLeague",position:"PG",  expected:"PnR Maestro",            ath:4,phys:2,vision:5, pF:"Never",                                       iF:"Secondary",iDec:"Finish",iDir:"Left",    co:"Attack Middle", pnrF:"Primary",  pnrRole:"Handler",  pnrP:"Pass First", vsU:"Reject / Attack",tF:"Primary",  indF:"Rare",    bkF:"Rare",  tR:"Pusher"   },
  { name:"Vasilije Micic",         league:"EuroLeague",position:"G",   expected:"Offensive Engine",       ath:3,phys:3,vision:4, pF:"Never",                                       iF:"Primary",  iDec:"Shoot", iDir:"Left",    co:"Catch & Shoot", pnrF:"Primary",  pnrRole:"Handler",  pnrP:"Balanced",   vsU:"Pull-up 3",      tF:"Secondary",indF:"Secondary",bkF:"Rare"   },
  { name:"Mathias Lessort",        league:"EuroLeague",position:"C",   expected:"Roll Man / Lob Threat",  ath:4,phys:5,vision:2, pF:"Secondary",                                   iF:"Never",                  iDir:"Balanced",co:"Extra Pass",    pnrF:"Primary",  pnrRole:"Screener", sA:"Roll",                              tF:"Primary",  indF:"Rare",    bkF:"Rare",  tR:"Rim Runner"},
  { name:"Markus Howard",          league:"EuroLeague",position:"G",   expected:"PnR Shooter",            ath:3,phys:2,vision:3, pF:"Never",                                       iF:"Secondary",iDec:"Shoot", iDir:"Right",   co:"Catch & Shoot", pnrF:"Primary",  pnrRole:"Handler",  pnrP:"Score First",vsU:"Pull-up 3",      tF:"Secondary",indF:"Primary", bkF:"Rare"   },
  { name:"Willy Hernangomez",      league:"EuroLeague",position:"C",   expected:"Low Post Scorer",        ath:2,phys:4,vision:3, pF:"Primary",  hasQ:true, pPro:"Back to Basket",  iF:"Rare",                   iDir:"Balanced",co:"Extra Pass",    pnrF:"Secondary",pnrRole:"Both",     pnrRS:"Screener",  pnrP:"Score First",vsU:"Re-screen",     sA:"Short Roll",tF:"Rare",     indF:"Rare",    bkF:"Rare"   },
  { name:"Pierria Henry",          league:"EuroLeague",position:"G",   expected:"Isolation Driver",       ath:5,phys:3,vision:3, pF:"Never",                                       iF:"Primary",  iDec:"Finish",iDir:"Right",   co:"Attack Baseline",pnrF:"Secondary",pnrRole:"Handler", pnrP:"Score First",vsU:"Reject / Attack",tF:"Primary",  indF:"Rare",    bkF:"Rare",  tR:"Pusher"   },
  { name:"Achille Polonara",       league:"EuroLeague",position:"F",   expected:"Spot-up Shooter",        ath:3,phys:3,vision:2, pF:"Never",                                       iF:"Rare",     iDec:"Shoot", iDir:"Balanced",co:"Catch & Shoot", pnrF:"Rare",     pnrRole:"Screener", sA:"Pop",                               tF:"Secondary",indF:"Rare",    bkF:"Rare",  tR:"Outlet"   },
  { name:"Thomas Walkup",          league:"EuroLeague",position:"G/F", expected:"3&D Wing",               ath:3,phys:3,vision:3, pF:"Never",                                       iF:"Rare",     iDec:"Shoot", iDir:"Balanced",co:"Catch & Shoot", pnrF:"Never",    pnrRole:"Screener", sA:"Pop",                               tF:"Rare",     indF:"Rare",    bkF:"Rare"   },
  { name:"Lorenzo Brown",          league:"EuroLeague",position:"G",   expected:"Combo Guard",            ath:3,phys:3,vision:4, pF:"Never",                                       iF:"Primary",  iDec:"Pass",  iDir:"Balanced",co:"Attack Middle", pnrF:"Secondary",pnrRole:"Handler",  pnrP:"Balanced",   vsU:"Re-screen",      tF:"Secondary",indF:"Rare",    bkF:"Rare"   },
  { name:"Evan Fournier",          league:"EuroLeague",position:"G/F", expected:"Movement Shooter",       ath:3,phys:3,vision:3, pF:"Never",                                       iF:"Secondary",iDec:"Shoot", iDir:"Right",   co:"Catch & Shoot", pnrF:"Rare",     pnrRole:"Handler",  pnrP:"Score First",vsU:"Pull-up 3",      tF:"Secondary",indF:"Primary", bkF:"Rare"   },
  // ── Generic edge cases ─────────────────────────────────────────────────────
  { name:"Pure 3&D Wing",          league:"Generic",   position:"F",   expected:"3&D Wing",               ath:3,phys:3,vision:2, pF:"Never",                                       iF:"Rare",     iDec:"Shoot", iDir:"Balanced",co:"Catch & Shoot", pnrF:"Never",    pnrRole:"Screener", sA:"Pop",                               tF:"Rare",     indF:"Rare",    bkF:"Rare"   },
  { name:"Interior Connector",     league:"Generic",   position:"F/C", expected:"Playmaking Big",         ath:3,phys:4,vision:5, pF:"Rare",                                        iF:"Rare",     iDec:"Pass",  iDir:"Balanced",co:"Extra Pass",    pnrF:"Primary",  pnrRole:"Both",     pnrRS:"Handler",   pnrP:"Pass First", vsU:"Re-screen",     sA:"Short Roll",tF:"Secondary",indF:"Rare",bkF:"Rare"   },
  { name:"Spot-up Corner Shooter", league:"Generic",   position:"F",   expected:"Spot-up Shooter",        ath:3,phys:3,vision:2, pF:"Never",                                       iF:"Rare",     iDec:"Shoot", iDir:"Balanced",co:"Catch & Shoot", pnrF:"Rare",     pnrRole:"Screener", sA:"Pop",                               tF:"Secondary",indF:"Never",   bkF:"Never", tR:"Outlet"   },
  { name:"Backdoor Cutter",        league:"Generic",   position:"F",   expected:"Cutting Threat",         ath:5,phys:3,vision:3, pF:"Never",                                       iF:"Rare",                   iDir:"Balanced",co:"Attack Middle", pnrF:"Rare",     pnrRole:"Screener", sA:"Roll",                              tF:"Primary",  indF:"Rare",    bkF:"Primary",tR:"Rim Runner"},
];
