path = '/Users/palant/Downloads/U scout/scripts/calibrate-motor.ts'
with open(path, 'r') as f:
    content = f.read()

new_profiles = """
  // ─── PERFILES ADICIONALES BATCH 2 — NBA/WNBA fiables + amateur + edge cases ──

  {
    id: "cal027",
    name: "Damian Lillard — ISO + PnR deep range",
    note: "Elite ISO scorer, clutch, deep 3PT, pull-up specialist, left hand dominant",
    inputs: {
      pos: "PG", hand: "R", ath: 4, phys: 3, usage: "primary",
      selfCreation: "high", starPlayer: true, personality: ["clutch"],
      isoFreq: "P", isoEff: "high", isoDir: "L", isoDec: "S",
      pnrFreq: "P", pnrEff: "high", pnrPri: "SF", trapResponse: "escape",
      pnrFinishLeft: "Pull-up", pnrFinishRight: "Drive to Rim",
      spotUpFreq: "S", deepRange: true,
      floater: "R", transFreq: "S",
      postFreq: "N", vision: 4, orebThreat: "low",
      contactFinish: "seeks", offHandFinish: "capable",
      cutFreq: "N", dhoFreq: "N", indirectFreq: "N",
      screenerAction: null, ballHandling: "elite", pressureResponse: "breaks",
    },
    expect: {
      deny_must: ["deny_iso_space", "deny_pnr_downhill"],
      force_must_not: ["force_early", "force_trap"],
      allow_must_not: ["allow_iso", "allow_spot_three"],
      top_situations: ["iso_left", "pnr_ball"],
      danger_min: 5,
      // Lillard attacks LEFT — his dominant side — so force_direction should go RIGHT
      force_text_contains: ["right"],
    },
  },

  {
    id: "cal028",
    name: "Devin Booker — ISO pull-up specialist",
    note: "Elite pull-up ISO, mid-range specialist AND 3PT, no weak hand issues, clutch",
    inputs: {
      pos: "SG", hand: "R", ath: 4, phys: 3, usage: "primary",
      selfCreation: "high", starPlayer: true, personality: ["clutch"],
      isoFreq: "P", isoEff: "high", isoDir: "R", isoDec: "S",
      pnrFreq: "S", pnrEff: "high", pnrPri: "SF", trapResponse: "pass",
      spotUpFreq: "S", deepRange: true,
      floater: "N", transFreq: "S",
      postFreq: "N", vision: 4, orebThreat: "low",
      contactFinish: "neutral", offHandFinish: "capable",
      cutFreq: "N", dhoFreq: "N", indirectFreq: "N",
      screenerAction: null, ballHandling: "elite", pressureResponse: "escapes",
    },
    expect: {
      deny_must: ["deny_iso_space"],
      force_must_not: ["force_trap", "force_early"],
      allow_must_not: ["allow_iso", "allow_spot_three"],
      top_situations: ["iso_right"],
      danger_min: 4,
      deny_text_contains: ["left", "right"],
    },
  },

  {
    id: "cal029",
    name: "Bam Adebayo — PnR Roll + Post",
    note: "PnR roll primary, face-up post, high phys, vision 4, no deep range, transition threat",
    inputs: {
      pos: "C", hand: "R", ath: 4, phys: 5, usage: "primary",
      selfCreation: "medium", starPlayer: true,
      screenerAction: "roll",
      pnrFreq: "S", pnrEff: "high",
      postFreq: "S", postEff: "high", postProfile: "FU",
      postShoulder: "R", postMoves: ["hook", "drop_step"],
      transFreq: "S", transRole: "rim_run",
      spotUpFreq: "N", deepRange: false,
      orebThreat: "high", putbackQuality: "capable",
      isoFreq: "N", vision: 4,
      contactFinish: "seeks", offHandFinish: "capable",
      floater: "N", cutFreq: "S", cutType: "basket",
      dhoFreq: "N", indirectFreq: "N",
      ballHandling: null, pressureResponse: null,
    },
    expect: {
      deny_must: ["deny_pnr_roll"],
      deny_must_not: ["deny_spot_deep", "deny_iso_space"],
      force_must_not: ["force_early"],
      allow_must: ["allow_spot_three"],
      top_situations: ["pnr_screener"],
      danger_min: 3,
    },
  },

  {
    id: "cal030",
    name: "Ja Morant — Transition + PnR Rim Attacker",
    note: "Elite transition, PnR Drive to Rim, ath=5, seeks contact, weak off-hand",
    inputs: {
      pos: "PG", hand: "R", ath: 5, phys: 3, usage: "primary",
      selfCreation: "high", starPlayer: true,
      pnrFreq: "P", pnrEff: "high", pnrPri: "SF", trapResponse: "escape",
      pnrFinishLeft: "Drive to Rim", pnrFinishRight: "Drive to Rim",
      isoFreq: "S", isoEff: "high", isoDir: "R", isoDec: "F",
      transFreq: "P", transRole: "rim_run", transRolePrimary: "rim_runner",
      transFinishing: "high",
      floater: "P",
      spotUpFreq: "N", deepRange: false,
      postFreq: "N", vision: 3,
      orebThreat: "low", contactFinish: "seeks", offHandFinish: "weak",
      cutFreq: "N", dhoFreq: "N", indirectFreq: "N",
      screenerAction: null, ballHandling: "elite", pressureResponse: "breaks",
    },
    expect: {
      deny_must: ["deny_pnr_downhill", "deny_trans_rim"],
      deny_must_not: ["deny_spot_deep"],
      force_must: ["force_weak_hand"],
      force_must_not: ["force_early"],
      allow_must: ["allow_spot_three"],
      top_situations: ["pnr_ball", "transition"],
      danger_min: 5,
    },
  },

  {
    id: "cal031",
    name: "Diana Taurasi — WNBA Veteran ISO + Spot-up",
    note: "Elite ISO + spot-up, deep range, vision élite, clutch player, aging but smart",
    inputs: {
      pos: "SG", hand: "R", ath: 3, phys: 2, usage: "primary",
      selfCreation: "high", starPlayer: true, personality: ["clutch"],
      isoFreq: "P", isoEff: "high", isoDir: "R", isoDec: "S",
      pnrFreq: "S", pnrPri: "SF", trapResponse: "escape",
      spotUpFreq: "P", spotZone: "wing", deepRange: true,
      floater: "N", transFreq: "R",
      postFreq: "N", vision: 5, orebThreat: "low",
      contactFinish: "avoids", offHandFinish: "capable",
      cutFreq: "N", dhoFreq: "N", indirectFreq: "N",
      screenerAction: null, ballHandling: "elite", pressureResponse: "escapes",
    },
    clubContext: { gender: "F" },
    expect: {
      deny_must: ["deny_iso_space", "deny_spot_deep"],
      force_must_not: ["force_contact", "force_early"],
      allow_must_not: ["allow_spot_three"],
      top_situations: ["iso_right", "catch_shoot"],
      danger_min: 4,
    },
  },

  {
    id: "cal032",
    name: "Draymond Green — Playmaking Big sin tiro",
    note: "Vision 5, sin tiro exterior, slip screener, high post passer, never ISO",
    inputs: {
      pos: "PF", hand: "R", ath: 3, phys: 4, usage: "role",
      selfCreation: "low",
      screenerAction: "slip", pnrScreenTiming: "ghost_touch",
      pnrFreq: "N",
      highPostZones: { leftElbow: "pass_to_cutter", rightElbow: "pass_to_cutter" },
      postFreq: "N",
      isoFreq: "N",
      spotUpFreq: "N", deepRange: false,
      cutFreq: "S", cutType: "basket",
      transFreq: "S", transRole: "fill",
      orebThreat: "medium", putbackQuality: "palms_only",
      vision: 5, floater: "N",
      dhoFreq: "N", indirectFreq: "N",
      contactFinish: "neutral", offHandFinish: "capable",
      ballHandling: null, pressureResponse: null,
    },
    expect: {
      deny_must: ["deny_pnr_slip", "deny_high_post_catch"],
      deny_must_not: ["deny_iso_space", "deny_spot_deep"],
      force_must_not: ["force_early"],
      allow_must: ["allow_spot_three"],
      alert_keys: ["aware_passer"],
      danger_min: 2,
      danger_max: 4,
    },
  },

  {
    id: "cal033",
    name: "Anthony Edwards — ISO Driver + 3PT",
    note: "ISO primary, drives right, spot-up secondary, elite ath, personality clutch",
    inputs: {
      pos: "SG", hand: "R", ath: 5, phys: 4, usage: "primary",
      selfCreation: "high", starPlayer: true, personality: ["clutch"],
      isoFreq: "P", isoEff: "high", isoDir: "R", isoDec: "F",
      pnrFreq: "S", pnrEff: "high", pnrPri: "SF",
      spotUpFreq: "S", deepRange: true,
      floater: "N", transFreq: "S", transRole: "rim_run",
      postFreq: "N", vision: 3, orebThreat: "low",
      contactFinish: "seeks", offHandFinish: "capable",
      cutFreq: "N", dhoFreq: "N", indirectFreq: "N",
      screenerAction: null, ballHandling: "elite", pressureResponse: "escapes",
      trapResponse: "pass",
    },
    expect: {
      deny_must: ["deny_iso_space"],
      force_must_not: ["force_trap", "force_contact"],
      allow_must_not: ["allow_iso", "allow_spot_three"],
      top_situations: ["iso_right"],
      danger_min: 5,
      force_text_contains: ["left"],
    },
  },

  {
    id: "cal034",
    name: "Nikola Vucevic — Post scorer mid-range",
    note: "Post face-up, mid-range shooter, no drive, high post, no transition",
    inputs: {
      pos: "C", hand: "R", ath: 2, phys: 4, usage: "primary",
      selfCreation: "high",
      postFreq: "P", postEff: "high", postProfile: "FU",
      postShoulder: "R", postMoves: ["turnaround", "fade"],
      highPostZones: { leftElbow: "pull_up", rightElbow: "pull_up" },
      isoFreq: "R", isoEff: "medium",
      spotUpFreq: "S", deepRange: false,
      pnrFreq: "R", transFreq: "N",
      orebThreat: "medium", putbackQuality: "capable",
      vision: 3, floater: "N",
      contactFinish: "neutral", offHandFinish: "capable",
      cutFreq: "N", dhoFreq: "N", indirectFreq: "N",
      screenerAction: null, ballHandling: null, pressureResponse: null,
    },
    expect: {
      deny_must: ["deny_post_entry", "deny_high_post_catch"],
      deny_must_not: ["deny_trans_rim", "deny_spot_deep"],
      force_must_not: ["force_early"],
      allow_must: ["allow_spot_three"],
      top_situations: ["post_right"],
      danger_min: 3,
      danger_max: 5,
    },
  },

  {
    id: "cal035",
    name: "Khris Middleton — Mid-range ISO + PnR",
    note: "ISO mid-range specialist, pull-up expert, PnR secondary, no transition",
    inputs: {
      pos: "SF", hand: "R", ath: 3, phys: 3, usage: "primary",
      selfCreation: "high", starPlayer: true,
      isoFreq: "P", isoEff: "high", isoDir: "R", isoDec: "S",
      pnrFreq: "S", pnrEff: "high", pnrPri: "SF",
      pnrFinishLeft: "Pull-up", pnrFinishRight: "Pull-up",
      spotUpFreq: "S", deepRange: false,
      floater: "N", transFreq: "R",
      postFreq: "N", vision: 4, orebThreat: "low",
      contactFinish: "neutral", offHandFinish: "capable",
      cutFreq: "N", dhoFreq: "N", indirectFreq: "N",
      screenerAction: null, ballHandling: "capable", pressureResponse: "escapes",
    },
    expect: {
      deny_must: ["deny_iso_space"],
      // No deepRange, pull-up PnR → allow_pnr_mid_range should appear
      allow_must: ["allow_pnr_mid_range"],
      force_must_not: ["force_early"],
      top_situations: ["iso_right"],
      danger_min: 3,
      danger_max: 5,
    },
  },

  {
    id: "cal036",
    name: "Trae Young — PnR floater specialist",
    note: "PnR primary, elite floater, deep range, vision 5, physically weak",
    inputs: {
      pos: "PG", hand: "R", ath: 2, phys: 1, usage: "primary",
      selfCreation: "high", starPlayer: true,
      pnrFreq: "P", pnrEff: "high", pnrPri: "PF", trapResponse: "escape",
      pnrFinishLeft: "Floater", pnrFinishRight: "Floater",
      isoFreq: "S", isoEff: "high",
      spotUpFreq: "S", deepRange: true,
      floater: "P",
      transFreq: "S", postFreq: "N",
      vision: 5, orebThreat: "low",
      contactFinish: "avoids", offHandFinish: "capable",
      cutFreq: "N", dhoFreq: "N", indirectFreq: "N",
      screenerAction: null, ballHandling: "elite", pressureResponse: "breaks",
    },
    expect: {
      deny_must: ["deny_pnr_downhill"],
      deny_must_not: ["deny_post_entry"],
      force_must_not: ["force_contact", "force_early", "force_trap"],
      allow_must_not: ["allow_spot_three"],
      top_situations: ["pnr_ball"],
      danger_min: 4,
      alert_keys: ["aware_passer"],
    },
  },

  {
    id: "cal037",
    name: "OG Anunoby — 3-and-D Wing elite",
    note: "Spot-up primario, sin creación, transition secondary, cortes ocasionales, phys fuerte",
    inputs: {
      pos: "SF", hand: "R", ath: 4, phys: 4, usage: "secondary",
      selfCreation: "low",
      spotUpFreq: "P", spotZone: "corner", deepRange: true,
      cutFreq: "S", cutType: "basket",
      transFreq: "S", transRole: "rim_run",
      isoFreq: "N", pnrFreq: "N", postFreq: "N",
      orebThreat: "medium",
      vision: 3, floater: "N",
      dhoFreq: "N", indirectFreq: "N",
      contactFinish: "neutral", offHandFinish: "capable",
      screenerAction: null, ballHandling: null, pressureResponse: null,
    },
    expect: {
      deny_must: ["deny_spot_corner"],
      deny_must_not: ["deny_iso_space", "deny_pnr_downhill"],
      force_must_not: ["force_trap", "force_early"],
      allow_must_not: ["allow_spot_three"],
      top_situations: ["catch_shoot"],
      danger_min: 2,
      danger_max: 5,
    },
  },

  {
    id: "cal038",
    name: "Arike Ogunbowale — WNBA ISO Scorer",
    note: "Elite ISO scorer WNBA, clutch, right hand dominant, pull-up + floater",
    inputs: {
      pos: "SG", hand: "R", ath: 4, phys: 3, usage: "primary",
      selfCreation: "high", starPlayer: true, personality: ["clutch"],
      isoFreq: "P", isoEff: "high", isoDir: "R", isoDec: "S",
      pnrFreq: "S", pnrEff: "medium", pnrPri: "SF",
      spotUpFreq: "S", deepRange: true,
      floater: "S", transFreq: "S",
      postFreq: "N", vision: 3, orebThreat: "low",
      contactFinish: "neutral", offHandFinish: "capable",
      cutFreq: "N", dhoFreq: "N", indirectFreq: "N",
      screenerAction: null, ballHandling: "elite", pressureResponse: "escapes",
    },
    clubContext: { gender: "F" },
    expect: {
      deny_must: ["deny_iso_space"],
      force_must_not: ["force_trap", "force_early"],
      allow_must_not: ["allow_spot_three"],
      top_situations: ["iso_right"],
      danger_min: 4,
      force_text_contains: ["left"],
    },
  },

  {
    id: "cal039",
    name: "Amateur — Base ofensiva sin tiro exterior",
    note: "Jugador amateur PG, PnR handler sin rango, sin creación real, nivel U18",
    inputs: {
      pos: "PG", hand: "R", ath: 3, phys: 2, usage: "primary",
      selfCreation: "high",
      pnrFreq: "P", pnrEff: "medium", pnrPri: "SF", trapResponse: "struggle",
      pnrFinishLeft: "Pull-up", pnrFinishRight: "Drive to Rim",
      isoFreq: "R", isoEff: "low",
      spotUpFreq: "R", deepRange: false,
      floater: "N", transFreq: "S",
      postFreq: "N", vision: 3, orebThreat: "low",
      contactFinish: "neutral", offHandFinish: "capable",
      cutFreq: "N", dhoFreq: "N", indirectFreq: "N",
      screenerAction: null, ballHandling: "capable", pressureResponse: null,
    },
    clubContext: { level: "developmental" },
    expect: {
      deny_must: ["deny_pnr_downhill"],
      force_must: ["force_trap"],
      allow_must: ["allow_spot_three"],
      top_situations: ["pnr_ball"],
      danger_min: 2,
      danger_max: 4,
    },
  },

  {
    id: "cal040",
    name: "Amateur — Interior sin habilidad",
    note: "C amateur, sin tiro, solo rebote y catch en pintua, nivel competitivo bajo",
    inputs: {
      pos: "C", hand: "R", ath: 2, phys: 4, usage: "role",
      selfCreation: "low",
      postFreq: "R", postEntry: "duck_in",
      screenerAction: "roll",
      isoFreq: "N", pnrFreq: "N",
      transFreq: "R", transRole: "rim_run",
      spotUpFreq: "N", deepRange: false,
      orebThreat: "high", putbackQuality: "capable",
      vision: 1, floater: "N",
      cutFreq: "N", dhoFreq: "N", indirectFreq: "N",
      contactFinish: "neutral", offHandFinish: "capable",
      ballHandling: "liability", pressureResponse: null,
    },
    clubContext: { level: "developmental" },
    expect: {
      deny_must: ["deny_pnr_roll"],
      deny_must_not: ["deny_iso_space", "deny_spot_deep"],
      force_must: ["force_no_ball"],
      allow_must: ["allow_spot_three"],
      danger_min: 1,
      danger_max: 4,
    },
  },

  {
    id: "cal041",
    name: "ACB — Ala-pívot versátil europeo",
    note: "PF europeo: post + spot-up, sin ISO, PnR screener pop, europeo nivel Euroleague",
    inputs: {
      pos: "PF", hand: "R", ath: 3, phys: 4, usage: "secondary",
      selfCreation: "medium",
      postFreq: "S", postEff: "high", postProfile: "B2B",
      postShoulder: "R", postMoves: ["hook", "fade"],
      screenerAction: "pop", deepRange: true,
      spotUpFreq: "S", spotZone: "wing",
      pnrFreq: "S",
      isoFreq: "N", transFreq: "R",
      orebThreat: "medium",
      vision: 3, floater: "N",
      contactFinish: "neutral", offHandFinish: "capable",
      cutFreq: "N", dhoFreq: "N", indirectFreq: "N",
      ballHandling: null, pressureResponse: null,
    },
    clubContext: { leagueType: "acb" },
    expect: {
      deny_must: ["deny_pnr_pop", "deny_post_entry"],
      deny_must_not: ["deny_iso_space"],
      force_must_not: ["force_early"],
      top_situations: ["pnr_screener", "post_right"],
      danger_min: 2,
      danger_max: 5,
    },
  },

  {
    id: "cal042",
    name: "Chinese Women's — Post técnica sin atletismo",
    note: "C WCBA: post técnica, fade + hook, phys alta, ath baja, sin transición",
    inputs: {
      pos: "C", hand: "R", ath: 1, phys: 5, usage: "primary",
      selfCreation: "high",
      postFreq: "P", postEff: "high", postProfile: "B2B",
      postShoulder: "L", postMoves: ["hook", "fade", "up_and_under"],
      postEntry: "seal",
      isoFreq: "N", pnrFreq: "N", transFreq: "N",
      spotUpFreq: "N", deepRange: false,
      orebThreat: "high", putbackQuality: "primary",
      vision: 2, floater: "N",
      contactFinish: "seeks", offHandFinish: "capable",
      cutFreq: "N", dhoFreq: "N", indirectFreq: "N",
      screenerAction: null, ballHandling: null, pressureResponse: null,
    },
    clubContext: { leagueType: "wcba", gender: "F" },
    expect: {
      deny_must: ["deny_post_entry"],
      deny_must_not: ["deny_trans_rim", "deny_spot_deep"],
      force_must_not: ["force_early"],
      allow_must: ["allow_spot_three"],
      top_situations: ["post_left"],
      danger_min: 3,
      alert_keys: ["aware_post_hook"],
    },
  },

  {
    id: "cal043",
    name: "Stretch Big — Interior espaciador puro",
    note: "PF: pop screener, spot-up deep range, sin ISO, sin post, solo aro por transición",
    inputs: {
      pos: "PF", hand: "R", ath: 3, phys: 3, usage: "secondary",
      selfCreation: "low",
      screenerAction: "pop", deepRange: true,
      spotUpFreq: "P", spotZone: "top",
      pnrFreq: "S",
      transFreq: "S", transRole: "trail",
      isoFreq: "N", postFreq: "N",
      orebThreat: "low",
      vision: 3, floater: "N",
      contactFinish: "neutral", offHandFinish: "capable",
      cutFreq: "N", dhoFreq: "N", indirectFreq: "N",
      ballHandling: null, pressureResponse: null,
    },
    expect: {
      deny_must: ["deny_pnr_pop", "deny_spot_deep"],
      deny_must_not: ["deny_iso_space", "deny_post_entry"],
      force_must_not: ["force_early"],
      allow_must_not: ["allow_spot_three"],
      top_situations: ["pnr_screener", "catch_shoot"],
      danger_min: 2,
      danger_max: 5,
    },
  },

  {
    id: "cal044",
    name: "Lethon Gizmo — Off-screen curler + spot-up",
    note: "Wing que vive de off-screens, curl threat, spot-up secondary, deepRange",
    inputs: {
      pos: "SG", hand: "R", ath: 4, phys: 2, usage: "secondary",
      selfCreation: "low",
      indirectFreq: "P", offBallCutAction: "curl",
      spotUpFreq: "S", deepRange: true,
      cutFreq: "S", cutType: "curl",
      isoFreq: "N", pnrFreq: "N", postFreq: "N",
      transFreq: "R", orebThreat: "low",
      vision: 3, floater: "N",
      dhoFreq: "N",
      contactFinish: "neutral", offHandFinish: "capable",
      screenerAction: null, ballHandling: null, pressureResponse: null,
    },
    expect: {
      deny_must: ["deny_off_ball_curl", "deny_spot_deep"],
      deny_must_not: ["deny_iso_space", "deny_pnr_downhill"],
      force_must_not: ["force_early", "force_trap"],
      top_situations: ["off_ball", "catch_shoot"],
      danger_min: 2,
      danger_max: 4,
    },
  },

  {
    id: "cal045",
    name: "Selfish ISO — baja eficiencia pero no para",
    note: "Jugador egoísta: siempre tira ISO aunque sea ineficiente, baja eficiencia",
    inputs: {
      pos: "SG", hand: "R", ath: 3, phys: 3, usage: "secondary",
      selfCreation: "medium", personality: ["selfish"],
      isoFreq: "P", isoEff: "low", isoDir: "R", isoDec: "S",
      pnrFreq: "N", postFreq: "N",
      spotUpFreq: "R", deepRange: false,
      transFreq: "R", orebThreat: "low",
      vision: 2, floater: "N",
      contactFinish: "neutral", offHandFinish: "capable",
      cutFreq: "N", dhoFreq: "N", indirectFreq: "N",
      screenerAction: null, ballHandling: "capable", pressureResponse: null,
    },
    expect: {
      // Selfish + low eff → allow_iso should appear (let them shoot bad shots)
      allow_must: ["allow_iso"],
      deny_must_not: ["deny_pnr_downhill", "deny_post_entry"],
      force_must_not: ["force_trap"],
      danger_min: 1,
      danger_max: 3,
    },
  },

  {
    id: "cal046",
    name: "DHO Specialist — handoff primario giver+receiver",
    note: "Jugadora que domina el DHO como tanto giver como receiver, spot-up secondary",
    inputs: {
      pos: "SG", hand: "R", ath: 3, phys: 2, usage: "secondary",
      selfCreation: "medium",
      dhoFreq: "P", dhoRole: "both", dhoAction: "shoot",
      spotUpFreq: "S", deepRange: true,
      isoFreq: "N", pnrFreq: "N", postFreq: "N",
      transFreq: "R", orebThreat: "low",
      vision: 3, floater: "N",
      contactFinish: "neutral", offHandFinish: "capable",
      cutFreq: "N", indirectFreq: "N",
      screenerAction: null, ballHandling: null, pressureResponse: null,
    },
    clubContext: { gender: "F" },
    expect: {
      deny_must: ["deny_dho"],
      deny_must_not: ["deny_pnr_downhill", "deny_post_entry"],
      force_must_not: ["force_trap", "force_early"],
      top_situations: ["dho"],
      danger_min: 2,
      danger_max: 5,
    },
  },

"""

insert_before = '\n];\n\n// ─── RUN CALIBRATION'
if insert_before in content:
    content = content.replace(insert_before, new_profiles + insert_before)
    with open(path, 'w') as f:
        f.write(content)
    print('OK — 20 new profiles added (cal027-cal046)')
else:
    print('NOT FOUND insert point')
