"""
Añadir 20 perfiles adicionales al calibrate-motor.ts
Jugadores reales con inputs precisos basados en datos Synergy/Basketball-Reference
"""

new_profiles = '''
  // ─── EUROLIGA / INTERNACIONALES ──────────────────────────────────────────

  {
    id: "cal027",
    name: "Vasilije Micic — EuroLeague PnR Maestro",
    note: "PnR handler pass-first, floater frecuente, deep range, escape artista vs traps",
    inputs: {
      pos: "PG", hand: "R", ath: 3, phys: 2, usage: "primary",
      selfCreation: "high",
      pnrFreq: "P", pnrEff: "high", pnrPri: "PF", trapResponse: "escape",
      pnrFinishLeft: "Floater", pnrFinishRight: "Pull-up",
      floater: "P",
      isoFreq: "S", isoEff: "medium",
      spotUpFreq: "S", deepRange: true,
      transFreq: "S",
      postFreq: "N",
      vision: 5, orebThreat: "low",
      cutFreq: "N", dhoFreq: "N", indirectFreq: "N",
      contactFinish: "neutral", offHandFinish: "capable",
      screenerAction: null, ballHandling: "elite", pressureResponse: "escapes",
    },
    expect: {
      deny_must: ["deny_pnr_downhill"],
      deny_must_not: ["deny_post_entry", "deny_oreb"],
      force_must_not: ["force_early", "force_trap"],
      allow_must_not: ["allow_spot_three"],
      top_situations: ["pnr_ball"],
      danger_min: 4,
      alert_keys: ["aware_passer"],
    },
  },

  {
    id: "cal028",
    name: "Nikola Mirotic — Stretch Big Euro",
    note: "PF con deep range, spot-up primario, PnR pop, sin juego de poste real",
    inputs: {
      pos: "PF", hand: "R", ath: 3, phys: 3, usage: "secondary",
      selfCreation: "medium",
      spotUpFreq: "P", spotZone: "top", deepRange: true,
      screenerAction: "pop",
      pnrFreq: "S", pnrEff: "medium",
      isoFreq: "R", postFreq: "R",
      transFreq: "R",
      orebThreat: "medium", // PF con algo de rebote
      vision: 3, floater: "N",
      cutFreq: "N", dhoFreq: "N", indirectFreq: "N",
      contactFinish: "neutral", offHandFinish: "capable",
      ballHandling: null, pressureResponse: null,
    },
    expect: {
      deny_must: ["deny_pnr_pop", "deny_spot_deep"],
      deny_must_not: ["deny_iso_space", "deny_post_entry"],
      force_must_not: ["force_early", "force_trap"],
      allow_must_not: ["allow_spot_three"],
      top_situations: ["pnr_screener", "catch_shoot"],
      danger_min: 3,
      danger_max: 5,
    },
  },

  {
    id: "cal029",
    name: "Shai Gilgeous-Alexander — ISO Scorer Elite",
    note: "ISO primario, va por la izquierda, seeks contact, floater, pull-up ambas manos",
    inputs: {
      pos: "SG", hand: "R", ath: 5, phys: 3, usage: "primary",
      selfCreation: "high", starPlayer: true,
      isoFreq: "P", isoEff: "high", isoDir: "L", isoDec: "F",
      pnrFreq: "S", pnrEff: "high", pnrPri: "SF",
      pnrFinishLeft: "Drive to Rim", pnrFinishRight: "Pull-up",
      floater: "S",
      spotUpFreq: "R", deepRange: false,
      transFreq: "S",
      postFreq: "N",
      vision: 4, orebThreat: "low",
      contactFinish: "seeks", offHandFinish: "capable",
      cutFreq: "N", dhoFreq: "N", indirectFreq: "N",
      screenerAction: null, ballHandling: "elite", pressureResponse: "escapes",
    },
    expect: {
      deny_must: ["deny_iso_space"],
      deny_must_not: ["deny_post_entry", "deny_spot_deep"],
      // seeks contact + no spotUp primary = force_contact valid
      allow_must_not: ["allow_iso", "allow_spot_three"],
      top_situations: ["iso_left"],
      danger_min: 5,
      deny_text_contains: ["left"],
    },
  },

  {
    id: "cal030",
    name: "Domantas Sabonis — Post + PnR Passer",
    note: "Post primario B2B, PnR pass-first, duck-in, oreb élite, high post passer",
    inputs: {
      pos: "C", hand: "R", ath: 3, phys: 5, usage: "primary",
      selfCreation: "high", starPlayer: true,
      postFreq: "P", postEff: "high", postProfile: "B2B",
      postShoulder: "R", postMoves: ["hook", "drop_step", "turnaround"],
      postEntry: "duck_in",
      highPostZones: { leftElbow: "pass_to_cutter", rightElbow: "face_up_drive" },
      pnrFreq: "S", pnrEff: "high", pnrPri: "PF", trapResponse: "escape",
      isoFreq: "N",
      transFreq: "R",
      spotUpFreq: "N", deepRange: false,
      orebThreat: "high", putbackQuality: "primary",
      contactFinish: "seeks", offHandFinish: "capable",
      vision: 4, floater: "N",
      cutFreq: "N", dhoFreq: "N", indirectFreq: "N",
      screenerAction: null, ballHandling: null, pressureResponse: null,
    },
    expect: {
      deny_must: ["deny_post_entry", "deny_duck_in"],
      deny_must_not: ["deny_spot_deep", "deny_iso_space"],
      allow_must_not: ["allow_iso", "allow_spot_three"],
      top_situations: ["post_right"],
      danger_min: 4,
      alert_keys: ["aware_passer"],
    },
  },

  {
    id: "cal031",
    name: "Devin Booker — ISO + PnR Scorer",
    note: "ISO y PnR handler, pull-up primario, mid-range specialist, deep range, clutch",
    inputs: {
      pos: "SG", hand: "R", ath: 4, phys: 3, usage: "primary",
      selfCreation: "high", starPlayer: true, personality: ["clutch"],
      isoFreq: "P", isoEff: "high", isoDir: "R", isoDec: "S",
      pnrFreq: "P", pnrEff: "high", pnrPri: "SF",
      pnrFinishLeft: "Pull-up", pnrFinishRight: "Pull-up",
      spotUpFreq: "S", deepRange: true,
      transFreq: "R",
      postFreq: "N",
      vision: 3, orebThreat: "low",
      floater: "N",
      contactFinish: "neutral", offHandFinish: "capable",
      cutFreq: "N", dhoFreq: "N", indirectFreq: "N",
      screenerAction: null, ballHandling: "elite", pressureResponse: "escapes",
    },
    expect: {
      deny_must: ["deny_iso_space", "deny_pnr_downhill"],
      deny_must_not: ["deny_post_entry", "deny_oreb"],
      // PnR handler with deepRange = no force_early
      force_must_not: ["force_early", "force_trap"],
      allow_must_not: ["allow_spot_three"],
      top_situations: ["iso_right", "pnr_ball"],
      danger_min: 4,
    },
  },

  {
    id: "cal032",
    name: "Jaylen Brown — Wing Scorer ISO",
    note: "ISO izquierda, drives al aro, contacto, sin rango exterior prioritario",
    inputs: {
      pos: "SG", hand: "R", ath: 5, phys: 4, usage: "primary",
      selfCreation: "high", starPlayer: true,
      isoFreq: "P", isoEff: "high", isoDir: "L", isoDec: "F",
      pnrFreq: "R", postFreq: "N",
      spotUpFreq: "S", deepRange: true,
      transFreq: "P", transRole: "rim_run", transRolePrimary: "rim_runner",
      transFinishing: "high",
      orebThreat: "low",
      contactFinish: "seeks", offHandFinish: "capable",
      vision: 3, floater: "N",
      cutFreq: "N", dhoFreq: "N", indirectFreq: "N",
      screenerAction: null, ballHandling: "capable", pressureResponse: null,
    },
    expect: {
      deny_must: ["deny_iso_space"],
      deny_must_not: ["deny_post_entry"],
      // seeks contact + no spotUp primary = force_contact valid here
      force_must_not: ["force_early"],
      allow_must_not: ["allow_iso"],
      top_situations: ["iso_left"],
      danger_min: 4,
      deny_text_contains: ["left"],
    },
  },

  {
    id: "cal033",
    name: "Anthony Davis — Post + PnR Roll",
    note: "Post y PnR screener roll, físico máximo, oreb élite, sin rango exterior",
    inputs: {
      pos: "C", hand: "R", ath: 5, phys: 5, usage: "primary",
      selfCreation: "high", starPlayer: true,
      postFreq: "P", postEff: "high", postProfile: "B2B",
      postShoulder: "L", postMoves: ["hook", "fade", "drop_step"],
      postEntry: "seal",
      screenerAction: "roll",
      pnrFreq: "S", pnrEff: "high",
      isoFreq: "R", isoDec: "F",
      transFreq: "S", transRole: "rim_run",
      transFinishing: "high",
      spotUpFreq: "N", deepRange: false,
      orebThreat: "high", putbackQuality: "primary",
      contactFinish: "seeks", offHandFinish: "capable",
      vision: 3, floater: "N",
      cutFreq: "N", dhoFreq: "N", indirectFreq: "N",
      ballHandling: null, pressureResponse: null,
    },
    expect: {
      deny_must: ["deny_post_entry", "deny_pnr_roll"],
      deny_must_not: ["deny_spot_deep", "deny_spot_corner"],
      force_must_not: ["force_early"],
      allow_must: ["allow_spot_three"],
      allow_must_not: ["allow_iso"],
      top_situations: ["post_left"],
      danger_min: 4,
    },
  },

  {
    id: "cal034",
    name: "Trae Young — PnR Maestro Floater",
    note: "PnR pass-first, floater élite, pull-up profundo, trap escape artista",
    inputs: {
      pos: "PG", hand: "R", ath: 2, phys: 1, usage: "primary",
      selfCreation: "high", starPlayer: true,
      pnrFreq: "P", pnrEff: "high", pnrPri: "PF", trapResponse: "escape",
      pnrFinishLeft: "Floater", pnrFinishRight: "Pull-up",
      floater: "P",
      isoFreq: "S", isoEff: "high",
      spotUpFreq: "S", deepRange: true,
      transFreq: "R",
      postFreq: "N",
      vision: 5, orebThreat: "low",
      cutFreq: "N", dhoFreq: "N", indirectFreq: "N",
      contactFinish: "avoids", offHandFinish: "capable",
      screenerAction: null, ballHandling: "elite", pressureResponse: "escapes",
    },
    expect: {
      deny_must: ["deny_pnr_downhill"],
      deny_must_not: ["deny_post_entry", "deny_oreb"],
      // phys=1 + avoids contact + deepRange = no force_contact, no force_early
      force_must_not: ["force_early", "force_trap", "force_contact"],
      allow_must_not: ["allow_spot_three"],
      top_situations: ["pnr_ball"],
      danger_min: 4,
      alert_keys: ["aware_passer"],
    },
  },

  {
    id: "cal035",
    name: "Khris Middleton — Wing Midrange Specialist",
    note: "ISO mid-range, PnR pull-up, no deepRange, timing-based creator, seeks contact",
    inputs: {
      pos: "SF", hand: "R", ath: 3, phys: 3, usage: "primary",
      selfCreation: "high",
      isoFreq: "P", isoEff: "high", isoDir: "R", isoDec: "S",
      pnrFreq: "S", pnrEff: "medium", pnrPri: "SF",
      pnrFinishLeft: "Pull-up", pnrFinishRight: "Pull-up",
      spotUpFreq: "R", deepRange: false,
      postFreq: "R", postEff: "medium",
      transFreq: "R",
      vision: 3, orebThreat: "low",
      floater: "N",
      contactFinish: "seeks", offHandFinish: "capable",
      cutFreq: "N", dhoFreq: "N", indirectFreq: "N",
      screenerAction: null, ballHandling: "capable", pressureResponse: null,
    },
    expect: {
      deny_must: ["deny_iso_space"],
      deny_must_not: ["deny_post_entry", "deny_spot_deep"],
      // ISO primary, no deepRange, no pnr primary → force_early valid
      force_must_not: ["force_trap"],
      allow_must: ["allow_spot_three"],
      top_situations: ["iso_right"],
      danger_min: 3,
      danger_max: 5,
    },
  },

  {
    id: "cal036",
    name: "Bam Adebayo — PnR Handler Big + DHO",
    note: "PF/C handler en PnR, DHO, post secundario, face-up, pasa primero",
    inputs: {
      pos: "PF", hand: "R", ath: 5, phys: 5, usage: "primary",
      selfCreation: "high", starPlayer: true,
      pnrFreq: "P", pnrEff: "high", pnrPri: "PF", trapResponse: "pass",
      pnrFinishLeft: "Drive to Rim", pnrFinishRight: "Drive to Rim",
      postFreq: "S", postEff: "medium", postProfile: "FU",
      postShoulder: "R",
      dhoFreq: "S", dhoRole: "giver", dhoAction: "pass",
      isoFreq: "N",
      transFreq: "S", transRole: "rim_run",
      transFinishing: "high",
      spotUpFreq: "N", deepRange: false,
      orebThreat: "high", putbackQuality: "capable",
      contactFinish: "seeks", offHandFinish: "capable",
      vision: 4, floater: "N",
      cutFreq: "N", indirectFreq: "N",
      screenerAction: null, ballHandling: "capable", pressureResponse: null,
    },
    expect: {
      deny_must: ["deny_pnr_downhill"],
      deny_must_not: ["deny_spot_deep", "deny_spot_corner"],
      // both sides Drive to Rim → no force_direction from asymmetry; PF handler
      force_must_not: ["force_early"],
      allow_must: ["allow_spot_three"],
      allow_must_not: ["allow_iso"],
      top_situations: ["pnr_ball"],
      danger_min: 4,
      alert_keys: ["aware_passer"],
    },
  },

  // ─── WNBA / EUROPA FEMENINO ───────────────────────────────────────────────

  {
    id: "cal037",
    name: "Diana Taurasi — Veteran ISO + PnR",
    note: "ISO y PnR, deep range, pull-up master, clutch, seeks contact",
    inputs: {
      pos: "SG", hand: "R", ath: 3, phys: 3, usage: "primary",
      selfCreation: "high", starPlayer: true, personality: ["clutch"],
      isoFreq: "P", isoEff: "high", isoDir: "R", isoDec: "S",
      pnrFreq: "S", pnrEff: "high", pnrPri: "SF",
      pnrFinishLeft: "Pull-up", pnrFinishRight: "Pull-up",
      spotUpFreq: "S", deepRange: true,
      transFreq: "R",
      postFreq: "N",
      vision: 4, orebThreat: "low",
      floater: "N",
      contactFinish: "seeks", offHandFinish: "capable",
      cutFreq: "N", dhoFreq: "N", indirectFreq: "N",
      screenerAction: null, ballHandling: "elite", pressureResponse: "escapes",
    },
    clubContext: { gender: "F" },
    expect: {
      deny_must: ["deny_iso_space", "deny_spot_deep"],
      deny_must_not: ["deny_post_entry"],
      force_must_not: ["force_early", "force_trap"],
      allow_must_not: ["allow_spot_three", "allow_iso"],
      top_situations: ["iso_right"],
      danger_min: 4,
    },
  },

  {
    id: "cal038",
    name: "Jonquel Jones — Stretch Big WNBA",
    note: "Interior con deep range, PnR pop, spot-up, poca amenaza de penetración",
    inputs: {
      pos: "PF", hand: "R", ath: 3, phys: 4, usage: "primary",
      selfCreation: "medium", starPlayer: true,
      spotUpFreq: "P", spotZone: "wing", deepRange: true,
      screenerAction: "pop",
      pnrFreq: "S", pnrEff: "medium",
      postFreq: "S", postEff: "medium", postProfile: "FU",
      isoFreq: "N",
      transFreq: "R",
      orebThreat: "medium",
      vision: 3, floater: "N",
      cutFreq: "N", dhoFreq: "N", indirectFreq: "N",
      contactFinish: "neutral", offHandFinish: "capable",
      ballHandling: null, pressureResponse: null,
    },
    clubContext: { gender: "F" },
    expect: {
      deny_must: ["deny_spot_deep", "deny_pnr_pop"],
      deny_must_not: ["deny_iso_space"],
      force_must_not: ["force_early", "force_trap"],
      allow_must_not: ["allow_spot_three"],
      top_situations: ["catch_shoot", "pnr_screener"],
      danger_min: 3,
      danger_max: 5,
    },
  },

  {
    id: "cal039",
    name: "Alyssa Thomas — Conector sin tiro",
    note: "DHO, PnR handler, sin tiro exterior, vision élite, contacto físico",
    inputs: {
      pos: "PF", hand: "R", ath: 4, phys: 4, usage: "primary",
      selfCreation: "high",
      dhoFreq: "P", dhoRole: "giver", dhoAction: "pass",
      pnrFreq: "S", pnrEff: "medium", pnrPri: "PF", trapResponse: "pass",
      pnrFinishLeft: "Drive to Rim", pnrFinishRight: "Drive to Rim",
      postFreq: "S", postEff: "medium",
      isoFreq: "N",
      transFreq: "S",
      spotUpFreq: "N", deepRange: false,
      orebThreat: "high", putbackQuality: "capable",
      contactFinish: "seeks", offHandFinish: "capable",
      vision: 5, floater: "N",
      cutFreq: "N", indirectFreq: "N",
      screenerAction: null, ballHandling: "capable", pressureResponse: null,
    },
    clubContext: { gender: "F" },
    expect: {
      deny_must: ["deny_dho", "deny_pnr_downhill"],
      deny_must_not: ["deny_spot_deep"],
      force_must_not: ["force_early"],
      allow_must: ["allow_spot_three"],
      allow_must_not: ["allow_iso"],
      top_situations: ["dho"],
      danger_min: 3,
      alert_keys: ["aware_passer"],
    },
  },

  // ─── PERFILES AMATEUR / SEMIPROFESIONAL ────────────────────────────────────

  {
    id: "cal040",
    name: "Base amateur — buen tirador sin creación",
    note: "Spot-up con rango, PnR handler secundario, poca creación propia, no elite",
    inputs: {
      pos: "PG", hand: "R", ath: 2, phys: 2, usage: "secondary",
      selfCreation: "medium",
      spotUpFreq: "P", spotZone: "corner", deepRange: true,
      pnrFreq: "S", pnrEff: "low", pnrPri: "SF",
      pnrFinishLeft: "Pull-up", pnrFinishRight: "Pull-up",
      isoFreq: "R", postFreq: "N",
      transFreq: "R",
      vision: 3, orebThreat: "low",
      floater: "N",
      contactFinish: "avoids", offHandFinish: "capable",
      cutFreq: "N", dhoFreq: "N", indirectFreq: "N",
      screenerAction: null, ballHandling: "capable", pressureResponse: null,
    },
    expect: {
      deny_must: ["deny_spot_corner"],
      deny_must_not: ["deny_post_entry", "deny_trans_rim"],
      force_must_not: ["force_early", "force_trap"],
      // avoids contact + spot-up primary = no force_contact
      force_must_not: ["force_contact"],
      allow_must_not: ["allow_spot_three"],
      top_situations: ["catch_shoot"],
      danger_min: 2,
      danger_max: 4,
    },
  },

  {
    id: "cal041",
    name: "Ala amateur — penetrador puro sin tiro",
    note: "Penetra siempre por su mano fuerte, sin tiro, sin post, físico mediocre",
    inputs: {
      pos: "SF", hand: "R", ath: 4, phys: 3, usage: "secondary",
      selfCreation: "medium",
      isoFreq: "P", isoEff: "medium", isoDir: "R", isoDec: "F",
      pnrFreq: "N", postFreq: "N",
      spotUpFreq: "N", deepRange: false,
      transFreq: "S",
      vision: 2, orebThreat: "low",
      floater: "N",
      contactFinish: "neutral", offHandFinish: "weak",
      cutFreq: "N", dhoFreq: "N", indirectFreq: "N",
      screenerAction: null, ballHandling: "capable", pressureResponse: null,
    },
    expect: {
      deny_must: ["deny_iso_space"],
      deny_must_not: ["deny_post_entry", "deny_spot_deep"],
      // weak off-hand → force_weak_hand or force_contact
      force_must: ["force_weak_hand"],
      allow_must: ["allow_spot_three"],
      top_situations: ["iso_right"],
      danger_min: 2,
      danger_max: 4,
      force_text_contains: ["hand"],
    },
  },

  {
    id: "cal042",
    name: "Pívot amateur — solo rebote y cortes",
    note: "C sin skills ofensivos, solo presencia física, sin tiro, roll o cortes",
    inputs: {
      pos: "C", hand: "R", ath: 2, phys: 4, usage: "role",
      selfCreation: "low",
      screenerAction: "roll",
      cutFreq: "S", cutType: "basket",
      postFreq: "N",
      transFreq: "S", transRole: "rim_run",
      transFinishing: "medium",
      orebThreat: "high", putbackQuality: "capable",
      isoFreq: "N", pnrFreq: "N",
      spotUpFreq: "N", deepRange: false,
      vision: 1, floater: "N",
      dhoFreq: "N", indirectFreq: "N",
      contactFinish: "neutral", offHandFinish: "capable",
      ballHandling: null, pressureResponse: null,
    },
    expect: {
      deny_must: ["deny_trans_rim", "deny_pnr_roll"],
      deny_must_not: ["deny_iso_space", "deny_spot_deep"],
      force_must_not: ["force_early"],
      allow_must: ["allow_spot_three"],
      allow_must_not: ["allow_iso"],
      top_situations: ["transition"],
      danger_min: 2,
      danger_max: 4,
    },
  },

  {
    id: "cal043",
    name: "Alero senior — experiencia sin atletismo",
    note: "ISO con timing, sin explosión, mid-range, visión media, no busca contacto",
    inputs: {
      pos: "SF", hand: "R", ath: 1, phys: 2, usage: "secondary",
      selfCreation: "medium",
      isoFreq: "S", isoEff: "medium", isoDir: "R", isoDec: "S",
      pnrFreq: "N", postFreq: "N",
      spotUpFreq: "S", deepRange: false,
      transFreq: "N",
      vision: 3, orebThreat: "low",
      floater: "N",
      contactFinish: "avoids", offHandFinish: "capable",
      cutFreq: "N", dhoFreq: "N", indirectFreq: "N",
      screenerAction: null, ballHandling: null, pressureResponse: null,
    },
    expect: {
      deny_must: ["deny_iso_space"],
      deny_must_not: ["deny_trans_rim", "deny_post_entry"],
      // ath=1 + selfCreation=high + iso=S → force_early valid (no exterior/trans threat)
      force_must_not: ["force_trap", "force_contact"],
      allow_must: ["allow_spot_three"],
      top_situations: ["iso_right"],
      danger_min: 1,
      danger_max: 3,
    },
  },

  {
    id: "cal044",
    name: "Escolta universitaria — off-screen y transición",
    note: "Off-screen primaria, catch-and-shoot, trail en transición, sin ISO",
    inputs: {
      pos: "SG", hand: "R", ath: 3, phys: 2, usage: "secondary",
      selfCreation: "low",
      indirectFreq: "P", offBallCutAction: "catch_and_shoot",
      spotUpFreq: "P", spotZone: "corner", deepRange: true,
      transFreq: "S", transRole: "trail", transRolePrimary: "trail",
      trailFrequency: "secondary", motorTransitionPrimary: "trail",
      transSubPrimary: "shoot_off_trail",
      isoFreq: "N", pnrFreq: "N", postFreq: "N",
      vision: 3, orebThreat: "low",
      floater: "N", dhoFreq: "N",
      contactFinish: "neutral", offHandFinish: "capable",
      screenerAction: null, ballHandling: null, pressureResponse: null,
    },
    expect: {
      deny_must: ["deny_spot_corner"],
      deny_must_not: ["deny_iso_space", "deny_pnr_downhill"],
      force_must_not: ["force_early", "force_trap"],
      allow_must_not: ["allow_spot_three"],
      top_situations: ["catch_shoot"],
      danger_min: 2,
      danger_max: 4,
    },
  },

  {
    id: "cal045",
    name: "Pivot universitario — post back-to-basket puro",
    note: "Post B2B sin rango, gancho y drop step, phys dominante, sin transición",
    inputs: {
      pos: "C", hand: "R", ath: 3, phys: 5, usage: "primary",
      selfCreation: "high",
      postFreq: "P", postEff: "high", postProfile: "B2B",
      postShoulder: "R", postMoves: ["hook", "drop_step"],
      postEntry: "seal",
      isoFreq: "N", pnrFreq: "N",
      transFreq: "N",
      spotUpFreq: "N", deepRange: false,
      orebThreat: "high", putbackQuality: "primary",
      contactFinish: "seeks", offHandFinish: "capable",
      vision: 2, floater: "N",
      cutFreq: "N", dhoFreq: "N", indirectFreq: "N",
      screenerAction: null, ballHandling: null, pressureResponse: null,
    },
    expect: {
      deny_must: ["deny_post_entry"],
      deny_must_not: ["deny_spot_deep", "deny_iso_space", "deny_pnr_downhill"],
      force_must_not: ["force_early"],
      allow_must: ["allow_spot_three"],
      allow_must_not: ["allow_iso"],
      top_situations: ["post_right"],
      danger_min: 3,
      alert_keys: ["aware_post_hook"],
    },
  },

  {
    id: "cal046",
    name: "Ala-pívot versátil — multiple threats",
    note: "PF con ISO, PnR handler, spot-up, post secundario — perfil complejo",
    inputs: {
      pos: "PF", hand: "R", ath: 4, phys: 4, usage: "primary",
      selfCreation: "high", starPlayer: true,
      isoFreq: "S", isoEff: "high", isoDir: "R", isoDec: "F",
      pnrFreq: "S", pnrEff: "high", pnrPri: "SF",
      pnrFinishLeft: "Pull-up", pnrFinishRight: "Drive to Rim",
      postFreq: "S", postEff: "medium", postProfile: "FU",
      spotUpFreq: "S", deepRange: true,
      transFreq: "S", transRole: "rim_run",
      orebThreat: "medium",
      contactFinish: "seeks", offHandFinish: "capable",
      vision: 4, floater: "S",
      cutFreq: "N", dhoFreq: "N", indirectFreq: "N",
      screenerAction: null, ballHandling: "capable", pressureResponse: "escapes",
    },
    expect: {
      deny_must: ["deny_spot_deep"],
      deny_must_not: ["deny_oreb"],
      force_must_not: ["force_early", "force_contact"],
      allow_must_not: ["allow_spot_three", "allow_iso"],
      danger_min: 4,
    },
  },

'''

path = '/Users/palant/Downloads/U scout/scripts/calibrate-motor.ts'
with open(path, 'r') as f:
    content = f.read()

insert_before = '\n];\n\n// ─── RUN CALIBRATION'
if insert_before in content:
    content = content.replace(insert_before, new_profiles + insert_before)
    with open(path, 'w') as f:
        f.write(content)
    print('OK — 20 new profiles added (cal027-cal046)')
else:
    print('NOT FOUND insert point')
    idx = content.rfind('];')
    print('Last ]; at:', idx)
